quadrantChart
    title "Innovation and User Experience of Online Art Platforms"
    x-axis "Low Innovation" --> "High Innovation"
    y-axis "Poor User Experience" --> "Great User Experience"
    quadrant-1 "May be improved"
    quadrant-2 "Re-evaluate"
    quadrant-3 "Need to promote"
    quadrant-4 "We should expand"
    "ArtStation": [0.2, 0.7]
    "Saatchi Art": [0.3, 0.8]
    "DeviantArt": [0.2, 0.6]
    "Artfinder": [0.3, 0.5]
    "Singulart": [0.4, 0.7]
    "ArtPal": [0.2, 0.5]
    "ConArtist Gallery": [0.9, 0.8]